/**
 * @title: GUIMenuPrincipal.java
 * @description: GUI de menu principal para el proyecto CadenaSuministros.
 * @date: Domingo 12 de noviembre de 2023
 * @version: 0.1
 * @author: Juan David Fajardo Betancourt y Leonardo Moreno Vargas
 */

package menusGUI;

//Imports de apis de java y sql 
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JMenu;
import Modelo.Producto;

//Clase del menu principal 
public class GUIMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuPrincipal
     */
    
    //Variables globales 
    Producto producto;
    private int tipoUSU;
    
    //Constructor 
    public GUIMenuPrincipal(int tipoUSU) {
        initComponents();
        this.tipoUSU = tipoUSU;
        mostrarNombre();
        producto = new Producto();
        producto.setImagen(producto.getImagen() + "logo.jpg");
        try{
            BufferedImage buf = ImageIO.read(new File(producto.getImagen()));
            ImageIcon icon = new ImageIcon(buf);
            Logo.setIcon(icon);
        }catch(IOException ex){
            System.out.println("La imagen no se insertó");
        }
    }
    
    //Imprime el nombre del tipo de usuario segun acceso 
    private void mostrarNombre(){
        switch(this.tipoUSU){
            case 1:
                Nombre.setText("Administrador");
            break;
            
            case 2:
                Nombre.setText("Bodeguero");
            break;
            
            case 3:
                Nombre.setText("Cliente");
            break;
            
            case 4:
                Nombre.setText("Vendedor");
            break;
            
            default:
            break;
        }
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem8 = new javax.swing.JMenuItem();
        Fondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1Usuarios = new javax.swing.JMenu();
        MenuAdministrador = new javax.swing.JMenuItem();
        MenuBodegueros = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenuItem();
        MenuVendedor = new javax.swing.JMenuItem();
        jMenu2Productos = new javax.swing.JMenu();
        MenuProductoHerraje = new javax.swing.JMenuItem();
        MenuProductoElectrico = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        Fondo.setBackground(new java.awt.Color(102, 102, 102));
        Fondo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Fondo.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setForeground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido!");

        Nombre.setFont(new java.awt.Font("Segoe UI Symbol", 0, 48)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 169, Short.MAX_VALUE))
                    .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jMenu1Usuarios.setBackground(new java.awt.Color(0, 255, 255));
        jMenu1Usuarios.setText("Manejador Usuarios                                                             ");

        MenuAdministrador.setText("Administrador");
        MenuAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdministradorActionPerformed(evt);
            }
        });
        jMenu1Usuarios.add(MenuAdministrador);

        MenuBodegueros.setText("Bodegueros");
        MenuBodegueros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBodeguerosActionPerformed(evt);
            }
        });
        jMenu1Usuarios.add(MenuBodegueros);

        MenuClientes.setText("Cliente");
        MenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClientesActionPerformed(evt);
            }
        });
        jMenu1Usuarios.add(MenuClientes);

        MenuVendedor.setText("Vendedor");
        MenuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVendedorActionPerformed(evt);
            }
        });
        jMenu1Usuarios.add(MenuVendedor);

        jMenuBar1.add(jMenu1Usuarios);

        jMenu2Productos.setText("Manejador Productos ");

        MenuProductoHerraje.setText("Productos Herraje");
        MenuProductoHerraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductoHerrajeActionPerformed(evt);
            }
        });
        jMenu2Productos.add(MenuProductoHerraje);

        MenuProductoElectrico.setText("Productos Electricos");
        MenuProductoElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductoElectricoActionPerformed(evt);
            }
        });
        jMenu2Productos.add(MenuProductoElectrico);

        jMenuBar1.add(jMenu2Productos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Se invoca al menu de admin (solo admin puede manipular los menus de usuario)
    private void MenuAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdministradorActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAdministrador().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuAdministradorActionPerformed

    //Se invoca al menu de bodegueros(solo admin puede manipular los menus de usuario)
    private void MenuBodeguerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBodeguerosActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIBodegueros().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuBodeguerosActionPerformed

    //  Se invoca al menu de clientes(solo el admin puede manipular los menus de usuarios)
    private void MenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICliente().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuClientesActionPerformed

    //Se invoca al menu de vendedores (solo el admin puede manipular los menus de usuario)
    private void MenuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVendedorActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIVendedor().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuVendedorActionPerformed

    //Se invoca al menu de productos de herrajes y se separa por un switch los roles
    //de cada usuario accedido 
    private void MenuProductoHerrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductoHerrajeActionPerformed
        // TODO add your handling code here:
        //Se hace un switch case con los 4 usuarios 
        switch (this.tipoUSU) {
            //Si el usuario es 1, accede como administrador 
            case 1:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new GUIProductosHerrajes().setVisible(true);
                    }
                });
            break;
            //Si el usuario es 2, accede como bodeguero y se desactivan
            //los campos que como bodeguero no puede manipular
            //unicamente puede manipular el id de la bodega 
            case 2:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        GUIProductosHerrajes prohe = new GUIProductosHerrajes();
                        prohe.getInsertar().setEnabled(false);
                        //prohe.getActualizar().setEnabled(false);
                        prohe.getBorrar().setEnabled(false);
                        
                        //prohe.getNS().setEnabled(false);
                        prohe.getNom().setEnabled(false);
                        prohe.getCol().setEnabled(false);
                        prohe.getMarc().setEnabled(false);
                        prohe.getMateri().setEnabled(false);
                        //prohe.getIdbodega().setEnabled(false);
                        prohe.getDemand().setEnabled(false);
                        prohe.getCP().setEnabled(false);
                        prohe.getCV().setEnabled(false);
                        prohe.getCA().setEnabled(false);
                        prohe.getTE().setEnabled(false);
                     
                        prohe.setVisible(true); 
                    }
                });
                
            break;
            //Si el usuario es 3, accede como cliente y por defecto
            //solo puede consultar y ordenar todos los productos 
            //el id solo esta disponible para consultar cada producto 
            case 3:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        GUIProductosHerrajes prohe = new GUIProductosHerrajes();
                        prohe.getInsertar().setEnabled(false);
                        prohe.getActualizar().setEnabled(false);
                        prohe.getBorrar().setEnabled(false);
                        
                        //prohe.getNS().setEnabled(false);
                        prohe.getNom().setEnabled(false);
                        prohe.getCol().setEnabled(false);
                        prohe.getMarc().setEnabled(false);
                        prohe.getMateri().setEnabled(false);
                        prohe.getIdbodega().setEnabled(false);
                        prohe.getDemand().setEnabled(false);
                        prohe.getCP().setEnabled(false);
                        prohe.getCV().setEnabled(false);
                        prohe.getCA().setEnabled(false);
                        prohe.getTE().setEnabled(false);
                     
                        prohe.setVisible(true); 
                    }
                });
            break;
            //Si el usuario es 4, accede como vendedor y solo puede 
            //manipular el costo de venta 
            case 4:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        GUIProductosHerrajes prohe = new GUIProductosHerrajes();
                        prohe.getInsertar().setEnabled(false);
                        //prohe.getActualizar().setEnabled(false);
                        prohe.getBorrar().setEnabled(false);
                        
                        //prohe.getNS().setEnabled(false);
                        prohe.getNom().setEnabled(false);
                        prohe.getCol().setEnabled(false);
                        prohe.getMarc().setEnabled(false);
                        prohe.getMateri().setEnabled(false);
                        prohe.getIdbodega().setEnabled(false);
                        prohe.getDemand().setEnabled(false);
                        prohe.getCP().setEnabled(false);
                        //prohe.getCV().setEnabled(false);
                        prohe.getCA().setEnabled(false);
                        prohe.getTE().setEnabled(false);
                     
                        prohe.setVisible(true); 
                    }
                });
            break;
            default:
                
            break;
        }
    }//GEN-LAST:event_MenuProductoHerrajeActionPerformed

    //Se invoca al menu de productos electricos y se separa por un switch los roles
    //de cada usuario accedido
    private void MenuProductoElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductoElectricoActionPerformed
        // TODO add your handling code here:
        //Se hace un switch case con los 4 usuarios
        switch (this.tipoUSU) {
            //Si el usuario es 1, accede como administrador
            case 1:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                       new GUIProductosElectricos().setVisible(true);
                    }
                });
            break;
            //Si el usuario es 2, accede como bodeguero y se desactivan
            //los campos que como bodeguero no puede manipular
            //unicamente puede manipular el id de la bodega
            case 2:
                    java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        GUIProductosElectricos proe = new GUIProductosElectricos();
                        proe.getInsertar().setEnabled(false);
                        //proe.getActualizar().setEnabled(false);
                        proe.getBorrar().setEnabled(false);
                        
                        //proe.getNS().setEnabled(false);
                        proe.getNom().setEnabled(false);
                        proe.getCol().setEnabled(false);
                        proe.getMarc().setEnabled(false);
                        proe.getMateri().setEnabled(false);
                        //proe.getIdbodega().setEnabled(false);
                        proe.getDemand().setEnabled(false);
                        proe.getCP().setEnabled(false);
                        proe.getCV().setEnabled(false);
                        proe.getCA().setEnabled(false);
                        proe.getCC().setEnabled(false);
                        proe.getCalibre().setEnabled(false);
                     
                        proe.setVisible(true); 
                    }
                });
            break;
            //Si el usuario es 3, accede como cliente y por defecto
            //solo puede consultar y ordenar todos los productos 
            //el id solo esta disponible para consultar cada producto
            case 3:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        GUIProductosElectricos proe = new GUIProductosElectricos();
                        proe.getInsertar().setEnabled(false);
                        proe.getActualizar().setEnabled(false);
                        proe.getBorrar().setEnabled(false);
                        
                        //proe.getNS().setEnabled(false);
                        proe.getNom().setEnabled(false);
                        proe.getCol().setEnabled(false);
                        proe.getMarc().setEnabled(false);
                        proe.getMateri().setEnabled(false);
                        proe.getIdbodega().setEnabled(false);
                        proe.getDemand().setEnabled(false);
                        proe.getCP().setEnabled(false);
                        proe.getCV().setEnabled(false);
                        proe.getCA().setEnabled(false);
                        proe.getCC().setEnabled(false);
                        proe.getCalibre().setEnabled(false);
                     
                        proe.setVisible(true); 
                    }
                });
            break;
            //Si el usuario es 4, accede como vendedor y solo puede 
            //manipular el costo de venta
            case 4:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        GUIProductosElectricos proe = new GUIProductosElectricos();
                        proe.getInsertar().setEnabled(false);
                        //proe.getActualizar().setEnabled(false);
                        proe.getBorrar().setEnabled(false);
                        
                        //proe.getNS().setEnabled(false);
                        proe.getNom().setEnabled(false);
                        proe.getCol().setEnabled(false);
                        proe.getMarc().setEnabled(false);
                        proe.getMateri().setEnabled(false);
                        proe.getIdbodega().setEnabled(false);
                        proe.getDemand().setEnabled(false);
                        proe.getCP().setEnabled(false);
                        //proe.getCV().setEnabled(false);
                        proe.getCA().setEnabled(false);
                        proe.getCC().setEnabled(false);
                        proe.getCalibre().setEnabled(false);
                     
                        proe.setVisible(true); 
                    }
                });
                
            break;    
            default:
                
            break;
        }
    }//GEN-LAST:event_MenuProductoElectricoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIMenuPrincipal().setVisible(true);
//            }
//        });
//    }

    //Getter
    public JMenu getjMenu1Usuarios() {
        return jMenu1Usuarios;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIMenuPrincipal().setVisible(true);
//            }
//        });
//    }
    //Setter 
    public void setjMenu1Usuarios(JMenu jMenu1Usuarios) {
        this.jMenu1Usuarios = jMenu1Usuarios;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JMenuItem MenuAdministrador;
    private javax.swing.JMenuItem MenuBodegueros;
    private javax.swing.JMenuItem MenuClientes;
    private javax.swing.JMenuItem MenuProductoElectrico;
    private javax.swing.JMenuItem MenuProductoHerraje;
    private javax.swing.JMenuItem MenuVendedor;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1Usuarios;
    private javax.swing.JMenu jMenu2Productos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
