/**
 * @title: GUIParcialFinal.java
 * @description: GUI del parcial para el proyecto CadenaSuministros.
 * @date: Lunes 27 de noviembre de 2023
 * @version: 0.1
 * @author: Juan David Fajardo Betancourt 
 */

package ParcialFinal;

//Imports de las clases 
import Controlador.ControladorProductosElectricos;
import Excepciones.Excepciones;
import Modelo.ProductosElectricos;
import javax.swing.JOptionPane;

//Clase del parcial final
public class GUIParcialFinal extends javax.swing.JFrame {

    /**
     * Creates new form GUIParcialFinal
     */
    
    //Variables Globales
    private ControladorProductosElectricos proEcont;
    ProductosElectricos producto;
    
    //Constructor
    public GUIParcialFinal() {
        initComponents();
        proEcont = new ControladorProductosElectricos();
        producto = new ProductosElectricos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        IMG = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NombrePE = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 15)); // NOI18N
        jLabel6.setText("Nombre del producto eléctrico");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Menú Parcial");

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Consulte el atributo solicitado ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14))
                .addContainerGap(1544, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NombrePE.setBackground(new java.awt.Color(51, 255, 204));
        NombrePE.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        NombrePE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombrePE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NombrePE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NombrePEFocusLost(evt);
            }
        });
        NombrePE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NombrePEMouseReleased(evt);
            }
        });
        NombrePE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(1040, 1040, 1040)
                        .addComponent(IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombrePE, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(NombrePE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243)
                .addComponent(IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Excepcion comentada
    private void NombrePEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombrePEFocusLost
        // TODO add your handling code here:
//        Excepciones excepcion = new Excepciones();
//        try{
//            excepcion.ValidarNombreProducto(NombrePE.getText());
//        } catch (Excepciones ex){
//            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
//            NombrePE.setText("");
//            NombrePE.requestFocus();
//        }
    }//GEN-LAST:event_NombrePEFocusLost

    private void NombrePEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePEActionPerformed

    //Evento mouse-release
    private void NombrePEMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombrePEMouseReleased
        // TODO add your handling code here:
        
        //Se valida que no este vacio
        if(NombrePE.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "El campo está vacío");
        }else{
            //Se separa memoria y se obtiene el evento con el texto  
            producto = new ProductosElectricos();
            producto.setNombre(NombrePE.getText());

            //Se invoca la excepcion 
            Excepciones excepcion = new Excepciones();
            //Se mete dentro de un try-catch
            try {
                //Se invoca al metodo de la excepcion 
                excepcion.ValidarNombreProducto(NombrePE.getText());
                //Si el nombre es correcto se valida con un mensaje de confirmacion 
                JOptionPane.showMessageDialog(rootPane , "El nombre del producto electrico '" + NombrePE.getText() + "' es correcto.");
              //De lo contrario llama a la excepcion   
            } catch (Excepciones ex) {
                //Imprime en pantalla el mensaje del error
                JOptionPane.showMessageDialog(rootPane , ex.getMessage());
                NombrePE.setText("");
                NombrePE.requestFocus();
            }
        }
        
    }//GEN-LAST:event_NombrePEMouseReleased

    /**
     * @param args the command line arguments
     */
    
    //Metodo main 
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIParcialFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIParcialFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIParcialFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIParcialFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIParcialFinal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel IMG;
    private javax.swing.JTextField NombrePE;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
